### ISSUE TITLE
WDIO Tests Blocked Due to Sauce Connect-related Bug

### ISSUE THREAD

**Issue by joshmgrant** [joshmgrant/99-minute-ci-cd-pipeline#1]
Currently WDIO tests aren't running correctly using Sauce Labs due to a bug with the Sauce Service. There is an open [pull request](https://github.com/webdriverio/webdriverio/pull/5961) for this on the Webdriverio GitHub. 

Once this bug is resolved the tests can be updated. In the meantime, you may want to consider:

- running WDIO tests without using Sauce Labs some way, or
- creating different functional tests that use another tool like [playwright](https://playwright.dev/).

**Comment by christian-bromann** [comment]
@joshmgrant WebdriverIO tests surely run correctly with Sauce Labs. The pull requests just adds a retry logic for Sauce Connect Proxy which should not be concerning for 99% of the user.

**Comment by joshmgrant** [comment]
Thanks for input @christian-bromann I appreciate it! It looks like updating to the latest version of WDIO and associated packages do fix this issue locally. However, there are still tunnel issues occurring on CircleCI. I will close this issue, however.
